### ISSUE TITLE
Set a price for the workshop

### ISSUE THREAD

**Issue by cheapjack** [mcqn/my-first-pcb#1]
Initially we are thinking around £65?

**Comment by cheapjack** [comment]
Maybe £39.99 if its just an online course. Depends if we want to provide materials. Maybe just 40 quid for an online only course?

**Comment by amcewen** [comment]
Mike Chitty had some good pricing options for this:
 * Free
 * £40 standard price
 * £80 standard and subsidize another place

Mostly what you're paying for is having access to me to answer questions on the day.

**Comment by cheapjack** [comment]
I've made it a bit more lefty

Free: If you cant afford it free no questions ask
Market Price £40, This is what we need to cover the costs
Solidarity Price £80, Feel like helping to subsidise other places
