### ISSUE TITLE
Set the date for the workshop

### ISSUE THREAD

**Issue by cheapjack** [mcqn/my-first-pcb#12]

**Comment by cheapjack** [comment]
@amcewen can we do Saturday 5th December if we doing wknd or Friday 4th? then Ill work on some copy next week

**Comment by amcewen** [comment]
Those work for me.  We should have a chat sometime next week - Weds or Fri? - to catch up properly on this.

**Comment by cheapjack** [comment]
Wednesday (except 2 -4) or Friday afternoon is good

**Comment by cheapjack** [comment]
Worth grabbing the date in the calendar but we can do that when we meet

**Comment by amcewen** [comment]
Weds at 10:30 work?  I'm free all day, so pick a time if not.

**Comment by cheapjack** [comment]
actually 11 would be perfect

**Comment by amcewen** [comment]
Works for me.  11 it is.

**Comment by cheapjack** [comment]
@amcewen we can use https://meet.jit.si/DomesticScience or whatever

**Comment by amcewen** [comment]
Hehe, *just* emailed you to suggest meet.coop, as that works better for me with Firefox.

**Comment by amcewen** [comment]
Done!  5th December it is.
