### ISSUE TITLE
Make course live

### ISSUE THREAD

**Issue by amcewen** [mcqn/my-first-pcb#2]
* [x] Pick a date
* [x] Write the Eventbrite page
* [ ] #Step2It

**Comment by amcewen** [comment]
In the Eventbrite signup details tell Windows users particularly that they should download and install Kicad (v5.1.5 or later) before the course, as it seems to take ~10 minutes to install.

**Comment by cheapjack** [comment]
@amcewen How about Saturday 5th December? DoES is free that day though that's maybe not important if it's an online thing, but I think always good to host via DoES to point people into further facilities even if really we are going to do this on jitsi or blue button or something.

We should probably set a deadline for copy for eventbrite

**Comment by cheapjack** [comment]
Im happy to post up and fiddle with formatting and adding an image if you want me to run a mcqn eventbrite? Be good so people can follow it who knows could become a lockdown earner for @amcewen :)

**Comment by amcewen** [comment]
Course is live and we have signups!
