### ISSUE TITLE
Document steps for My First #BadgeLife

### ISSUE THREAD

**Issue by amcewen** [mcqn/my-first-pcb#3]
Write up the steps to design a simple LED badge: schematic; circuit; generating gerbers and BOM

**Comment by amcewen** [comment]
1-Click-BOM is at https://github.com/kitspace/1clickBOM

**Comment by cheapjack** [comment]
I've made a quick start on filling in the steps but I'm kinda stuck at the generate netlist section as I don't fully know what I'm doing... I'll dig out some Kicad tutorials for reference and get you to fact/process check later on ;)

**Comment by amcewen** [comment]
Have picked away at this a bit.

Re-jigged the indenting to fix the automatic numbering.  Seems you have to indent things to match where the main text of the list item started (i.e. 3 spaces for numbered lists, 2 spaces for unordered lists)

And then moved things between some of the sections to match the titles.  I'll have a look at the netlist and so on next, and run through the PCB layout to generate a bunch of new screenshots.

**Comment by amcewen** [comment]
We should stick the battery and resistor on the back of the PCB and the LED on the front, which also lets us explain vias, etc.

Having two options: one for through-hole and one for surface-mount.

**Comment by amcewen** [comment]
Finished writing this all up.
